#!/usr/bin/env sh
chmod +x $(dirname "$0")/cmd-nix/*.sh
echo -en "\033]0;websites on the internet\a"
if [ $# -eq 0 ]
    then
        lua $(dirname "$0")/main.lua $(dirname "$0")
    else 
        lua $(dirname "$0")/main.lua $(dirname "$0") $1
fi

