-- Put your personal settings here, e.g.
-- 
-- PLATFORM = 3
--
-- BOOKMARKS_FILE="C:/bookmarks.txt"
--
-- BROWSER_CMD = {
--     "start firefox -new-tab %s",
--     "start chrome %s",
--     "start %s",
--     "start edge %s"
-- }
-- ...
