-- Put your personal settings here, e.g.
--
-- BOOKMARKS_FILE="C:/bookmarks.txt"
--
-- CLIPBOARD_CMD="clip"
--
-- BROWSER_CMD = {
--     "start firefox -new-tab %s",
--     "start chrome %s",
--     "start %s",
--     "start edge %s"
-- }
-- ...
